[tool.poetry]
name = "streamlit-rxdb-dataframe"
version = "0.1.0"
description = ""
authors = ["voznik <github.com/voznik>"]
readme = "README.md"
packages = [{include = "streamlit-rxdb-dataframe"}]

[tool.poetry.dependencies]
python = "^3.10"
pytest-playwright = "^0.4.4"
streamlit = "^1.31.0"
pyperclip = "^1.8.2"
python-dotenv = "^1.0.1"
playwright = "^1.41.2"
pandas = "^2.2.1"
streamlit-superapp = "^1.3.0"
streamlit-parameters = "^0.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
