[tool.poetry]
name = "streamlit-rxdb-dataframe"
version = "0.1.0"
description = "Custom streamlit component connecting local browser indexedDB database as RxDB collection as dataframe"
authors = ["voznik <mrvoznik@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/voznik/ngx-odm"
repository = "https://github.com/voznik/ngx-odm"
keywords = ["streamlit", "indexedDB", "RxDB", "browser", "connection", "dataframe"]
packages = [{ include = "rxdb_dataframe" }]

[tool.poetry.dependencies]
python = "^3.10"
pytest-playwright = "^0.4.4"
streamlit = "^1.31.0"
playwright = "^1.41.2"
pandas = "^2.2.1"
jsonschema = "^4.21.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
black = "^23.1.0"
isort = "^5.12.0"
mypy = "^1.0.0"
flake8 = "^7.0.0"
flake8-annotations-complexity = "^0.0.8"

[tool.isort]
profile = "black"
line_length = 100
skip = ["./.venv", "./direnv", ".env"]

[tool.black]
exclude = '''
(
  /(
      \.vscode
    | \.git
    | \.pytest_cache
    | \.mypy_cache
    | \.venv
    | \.env
    | \.direnv
  )/
)
'''
include = '\.pyi?$'
line-length = 100

[tool.flake8]
max-line-length = 100
ignore = ["E501"]

[tool.mypy]
files = ["**/*.py"]
follow_imports = "silent"
ignore_missing_imports = true
scripts_are_modules = true
python_version = "3.9"


[tool.ruff]
exclude = [
  ".git",
  ".vscode",
  ".pytest_cache",
  ".mypy_cache",
  ".venv",
  ".env",
  ".direnv",
  "streamlit_patches.py",
]
target-version = "py310"
ignore = ["E501"]
line-length = 100
select = ["B", "E", "F", "W", "I"]

[tool.ruff.per-file-ignores]
